[cerebrium.deployment]
name = "voice-pipeline-airgapped"
python_version = "3.11"
include = ["./*", "src/*.py", "cerebrium.toml"]
exclude = [".*", "venv", "__pycache__", "*.pyc", "node_modules", "local_client.py","client"]
# docker_base_image_url = "nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04"  # Commented out - using custom Dockerfile

[cerebrium.runtime.custom]
port = 8000
entrypoint = "python src/main.py"
healthcheck_endpoint = "/health"
readycheck_endpoint = "/ready"
dockerfile_path = "./docker/Dockerfile"

[cerebrium.hardware]
cpu = 8
memory = 24.0
compute = "AMPERE_A10"
gpu_count = 1
provider = "aws"
region = "eu-west-2"

[cerebrium.scaling]
min_replicas = 0        # Keep one replica warm to avoid cold starts
max_replicas = 2
cooldown = 300
response_grace_period = 900   # Keep long voice sessions alive (15 min)

[cerebrium.secrets]
HF_TOKEN = "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"
# NO OPENAI_API_KEY - Air-gapped deployment

[cerebrium.environment]
PIPER_MODEL = "en_US-lessac-medium"
PIPER_SAMPLE_RATE = "22050"
SERVICE_PREFIX = "/v4/p-468ff80b/voice-pipeline-airgapped"
EXTERNAL_HOST = "api.cortex.cerebrium.ai"

